services:
  frontend:
    image: node-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      VITE_PORT: ${VITE_PORT}
    ports:
      - 8080:8080

  backend:
    image: node-backend
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGO_URI: ${MONGO_URI}
    ports:
      - "3000:${BACKEND_PORT}"
    depends_on:
      - mongo

  mongo:
    image: mongo:jammy
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Mongo express allows us to inspect the contents of the db
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: ${MONGO_EXPRESS_PORT}
    ports:
      - "0.0.0.0:${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}"
    depends_on:
      - mongo

volumes:
  mongo_data:
    name: mongo_data_prod
