services:
  node:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development  
      - MONGO_URI=mongodb://mongo:27017/workshop-ecommerce  
    volumes:
      - ./:/home/node/app
    ports:
      - "5173:5173" 
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - mongo  

  mongo:
    image: mongo:jammy
    restart: always
    ports:
      - "27017:27017"  
    volumes:
      - mongo_data:/data/db  

volumes:
  mongo_data:  
